In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
url = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/auto.csv"

In [4]:
df=pd.read_csv(url)

In [5]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [6]:
df.columns=headers

In [7]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [8]:
df["symboling"]= df["symboling"] + 1 # adding values to the columns (here 1 added to symboling column)

In [9]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,3,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,3,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,3,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [10]:
df.dropna(subset = ["normalized-losses"], axis = 0 , inplace = True) 
# deleting row (axis =0) deleting column (axis=1) for missing vals

In [11]:
mean = df["symboling"].mean() # take mean for missing numerical values and then replace missing vals with the mean
# mode taken for categorical variables

In [12]:
df["symboling"].replace(3,mean) 
# after mean is taken replace the missing vals with the mean (here 3 replace with mean of the symboling column)

0      4.000000
1      2.000000
2      1.823529
3      1.823529
4      1.823529
         ...
199    0.000000
200    0.000000
201    0.000000
202    0.000000
203    0.000000
Name: symboling, Length: 204, dtype: float64

In [13]:
df["city-mpg"]= 235/df["city-mpg"]# to make calculations in all values of a column (here mpg changed to mp-L of city)

In [14]:
df.head(5) # sucessfully converted and performed calculation on the city mpg column

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
1,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
2,3,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
3,3,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
4,3,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250

In [15]:
df.rename(columns={"city-mpg":"city-mp-L"},inplace=True) 
# rename column where calculation done appropriatley(inplace=True)

In [16]:
df.head(5)# display to check

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
1,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
2,3,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
3,3,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
4,3,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250

In [17]:
df["wheel-base"]=df["wheel-base"]/df["wheel-base"].max() 
# normalizing a column by simple feature scaling method (here,wheel base column)

In [18]:
df.head(5) # check results

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,0.732837,...,130,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
1,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,0.781638,...,152,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
2,3,164,audi,gas,std,four,sedan,fwd,front,0.825476,...,109,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
3,3,164,audi,gas,std,four,sedan,4wd,front,0.822167,...,136,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
4,3,?,audi,gas,std,two,sedan,fwd,front,0.825476,...,136,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250

In [19]:
df["engine-size"]=(df["engine-size"]-df["engine-size"].min())/(df["engine-size"].max()-df["engine-size"].min())
# normalizing a column using min-max method i.e. xnew=xold-xmin/xmax-xmin (here column is engine-size)

In [20]:
df.head(10) #check it!!

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price
0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,0.732837,...,0.260377,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
1,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,0.781638,...,0.343396,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
2,3,164,audi,gas,std,four,sedan,fwd,front,0.825476,...,0.181132,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
3,3,164,audi,gas,std,four,sedan,4wd,front,0.822167,...,0.283019,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
4,3,?,audi,gas,std,two,sedan,fwd,front,0.825476,...,0.283019,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250
5,2,158,audi,gas,std,four,sedan,fwd,front,0.875103,...,0.283019,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,17710
6,2,?,audi,gas,std,four,wagon,fwd,front,0.875103,...,0.283019,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,18920
7,2,158,audi,gas,turbo,four,sedan,fwd,front,0.875103,...,0.264151,mpfi,3.13,3.40,8.3,140,5500,13.823529,20,23875
8,1,?,audi,gas,turbo,two,hatchback,4wd,front,0.822994,...,0.264151,mpfi,3.13,3.40,7.0,160,5500,14.687500,22,?
9,3,192,bmw,gas,std,two,sedan,rwd,front,0.837055,...,0.177358,mpfi,3.50,2.80,8.8,101,5800,10.217391,29,16430

In [21]:
df["symboling"]=(df["symboling"]-df["symboling"].mean())/df["symboling"].std() 
#normalizing the column with z score method i.e. xnew=x-mu/sigma (here column normalized is symboling)

In [22]:
df.head(5) #success!!

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price
0,1.756586,?,alfa-romero,gas,std,two,convertible,rwd,front,0.732837,...,0.260377,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500
1,0.142426,?,alfa-romero,gas,std,two,hatchback,rwd,front,0.781638,...,0.343396,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500
2,0.949506,164,audi,gas,std,four,sedan,fwd,front,0.825476,...,0.181132,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950
3,0.949506,164,audi,gas,std,four,sedan,4wd,front,0.822167,...,0.283019,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450
4,0.949506,?,audi,gas,std,two,sedan,fwd,front,0.825476,...,0.283019,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250

In [23]:
df.price = pd.to_numeric(df.price, errors='coerce').fillna(0).astype(np.int64) 
# converted price column to int by this method as was having problems

In [24]:
bins = np.linspace(min(df["price"]), max(df["price"]), 4)
# binning (grouping of values here price into 3 categories) the column using 4 dividers using linspace function

In [25]:
group_names = ["Low","Medium","High"] # divinding the grouped values into categories respectively

In [26]:
df["price-binned"] = pd.cut(df["price"],bins,labels=group_names,include_lowest=True) 
# after grouping,cutting into segments and sorting data values into bins using pandas' cut function

In [27]:
df.head() # Check the new column price-binned categories have been created i.e. low,medium,high for the column

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price,price-binned
0,1.756586,?,alfa-romero,gas,std,two,convertible,rwd,front,0.732837,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500,Medium
1,0.142426,?,alfa-romero,gas,std,two,hatchback,rwd,front,0.781638,...,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500,Medium
2,0.949506,164,audi,gas,std,four,sedan,fwd,front,0.825476,...,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950,Low
3,0.949506,164,audi,gas,std,four,sedan,4wd,front,0.822167,...,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450,Medium
4,0.949506,?,audi,gas,std,two,sedan,fwd,front,0.825476,...,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250,Medium

In [28]:
pd.get_dummies(df['fuel-type']) 
#To convert a columns categorical to numerical values first convert them by assigning them dummy variables (0/1)
#(here coln fuel-type)

     diesel  gas
0         0    1
1         0    1
2         0    1
3         0    1
4         0    1
..      ...  ...
199       0    1
200       0    1
201       0    1
202       1    0
203       0    1

[204 rows x 2 columns]

In [29]:
df.head(15) # check here that the column has been assigned dummy vars (here 0 for one feature 1 for other feature)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mp-L,highway-mpg,price,price-binned
0,1.756586,?,alfa-romero,gas,std,two,convertible,rwd,front,0.732837,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500,Medium
1,0.142426,?,alfa-romero,gas,std,two,hatchback,rwd,front,0.781638,...,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500,Medium
2,0.949506,164,audi,gas,std,four,sedan,fwd,front,0.825476,...,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950,Low
3,0.949506,164,audi,gas,std,four,sedan,4wd,front,0.822167,...,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450,Medium
4,0.949506,?,audi,gas,std,two,sedan,fwd,front,0.825476,...,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,15250,Medium
5,0.142426,158,audi,gas,std,four,sedan,fwd,front,0.875103,...,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,17710,Medium
6,0.142426,?,audi,gas,std,four,wagon,fwd,front,0.875103,...,mpfi,3.19,3.40,8.5,110,5500,12.368421,25,18920,Medium
7,0.142426,158,audi,gas,turbo,four,sedan,fwd,front,0.875103,...,mpfi,3.13,3.40,8.3,140,5500,13.823529,20,23875,Medium
8,-0.664654,?,audi,gas,turbo,two,hatchback,4wd,front,0.822994,...,mpfi,3.13,3.40,7.0,160,5500,14.687500,22,0,Low
9,0.949506,192,bmw,gas,std,two,sedan,rwd,front,0.837055,...,mpfi,3.50,2.80,8.8,101,5800,10.217391,29,16430,Medium
10,-0.664654,192,bmw,gas,std,four,sedan,rwd,front,0.837055,...,mpfi,3.50,2.80,8.8,101,5800,10.217391,29,16925,Medium
11,-0.664654,188,bmw,gas,std,two,sedan,rwd,front,0.837055,...,mpfi,3.31,3.19,9.0,121,4250,11.190476,28,20970,Medium
12,-0.664654,188,bmw,gas,std,four,sedan,rwd,front,0.837055,...,mpfi,3.31,3.19,9.0,121,4250,11.190476,28,21105,Medium
13,0.142426,?,bmw,gas,std,four,sedan,rwd,front,0.856079,...,mpfi,3.31,3.19,9.0,121,4250,11.750000,25,24565,Medium
14,-0.664654,?,bmw,gas,std,four,sedan,rwd,front,0.856079,...,mpfi,3.62,3.39,8.0,182,5400,14.687500,22,30760,High

In [30]:
dummy_variable_1=pd.get_dummies(df['body-style']) 
#example for more than 2 variables assign dummy_variable_1 to dummy vars created after assinging them to body style

In [31]:
df = pd.concat([df, dummy_variable_1], axis=1) #merge df to dummy_variable_1

In [32]:
df.drop("body-style", axis = 1, inplace=True) 
#drop the column (originally body style) as replace with dummy vars no of each category (0/1)

In [33]:
print(dummy_variable_1)

     convertible  hardtop  hatchback  sedan  wagon
0              1        0          0      0      0
1              0        0          1      0      0
2              0        0          0      1      0
3              0        0          0      1      0
4              0        0          0      1      0
..           ...      ...        ...    ...    ...
199            0        0          0      1      0
200            0        0          0      1      0
201            0        0          0      1      0
202            0        0          0      1      0
203            0        0          0      1      0

[204 rows x 5 columns]

In [34]:
# Below are additional statements a/c to jupyter labs in the module 2

In [35]:
missing_data=df.isnull() # For checking values missing or not isnull() used (False for not missing True for missing)

In [36]:
missing_data.head(20) # Checking

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,drive-wheels,engine-location,wheel-base,length,...,peak-rpm,city-mp-L,highway-mpg,price,price-binned,convertible,hardtop,hatchback,sedan,wagon
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [70]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    
# to count missing values in each column run a for loop

symboling
False    204
Name: symboling, dtype: int64

normalized-losses
False    204
Name: normalized-losses, dtype: int64

make
False    204
Name: make, dtype: int64

fuel-type
False    204
Name: fuel-type, dtype: int64

aspiration
False    204
Name: aspiration, dtype: int64

num-of-doors
False    204
Name: num-of-doors, dtype: int64

body-style
False    204
Name: body-style, dtype: int64

drive-wheels
False    204
Name: drive-wheels, dtype: int64

engine-location
False    204
Name: engine-location, dtype: int64

wheel-base
False    204
Name: wheel-base, dtype: int64

length
False    204
Name: length, dtype: int64

width
False    204
Name: width, dtype: int64

height
False    204
Name: height, dtype: int64

curb-weight
False    204
Name: curb-weight, dtype: int64

engine-type
False    204
Name: engine-type, dtype: int64

num-of-cylinders
False    204
Name: num-of-cylinders, dtype: int64

engine-size
False    204
Name: engine-size, dtype: int64

fuel-system
False    204
Name: fuel-system, dtype: int64

bore
False    204
Name: bore, dtype: int64

stroke
False    204
Name: stroke, dtype: int64

compression-ratio
False    204
Name: compression-ratio, dtype: int64

horsepower
False    204
Name: horsepower, dtype: int64

peak-rpm
False    204
Name: peak-rpm, dtype: int64

city-mp-L
False    204
Name: city-mp-L, dtype: int64

highway-mpg
False    204
Name: highway-mpg, dtype: int64

price
False    204
Name: price, dtype: int64

In [88]:
df['drive-wheels'].value_counts() # to count which vals/no of vals are present in a particular column

fwd    120
rwd     75
4wd      9
Name: drive-wheels, dtype: int64

In [89]:
df['drive-wheels'].value_counts().idxmax() # to find the most common type among all the vals of the column

'fwd'

     convertible  hardtop  hatchback  sedan  wagon
0              1        0          0      0      0
1              0        0          1      0      0
2              0        0          0      1      0
3              0        0          0      1      0
4              0        0          0      1      0
..           ...      ...        ...    ...    ...
199            0        0          0      1      0
200            0        0          0      1      0
201            0        0          0      1      0
202            0        0          0      1      0
203            0        0          0      1      0

[204 rows x 5 columns]